name: Catalog CI #Titel für den Workflow

on: # Trigger für den Workflow
  push: # Bei jedem Push ins Repository (egal welcher Branch)
  pull_request: # Bei jedem Pull Request ins Repository (egal welcher Branch)

jobs: # Definition der Jobs (build, test, deploy, etc.)
  build:
    runs-on: ubuntu-latest # Job läuft auf einem Ubuntu-Linux Runner

    steps: # Schritte des Jobs
      - uses: actions/checkout@v5 # Code aus dem Repository auschecken

      - name: Set up Java # Einrichtung von Java 21
        uses: actions/setup-java@v4 #Github Action zum Einrichten von Java
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Repository # Maven Repository cachen (Bonus)
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven # Maven Build & Test
        run: mvn --batch-mode --update-snapshots verify # beinhaltet compile, unit-tests, integration tests, package, verify

      - name: Build Docker Image with Buildpacks # Docker Image mit Spring Boot Buildpacks bauen
        run: mvn spring-boot:build-image # Befehl zum Bauen des Docker Images mit Buildpacks
        # Buildpack erkennt automatisch: Base Image, JDK Runtime, App kopieren (Layering), Dependencies, Entrypoint

      - name: Docker Login # Login in Docker Hub
        uses: docker/login-action@v3 # Github Action zum Login in Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub Username aus GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub Token aus GitHub Secrets

      - name: Tag and Push Image # Docker Image taggen und pushen
        run: | # Mehrzeiliger Befehl / Image taggen / Image zu Docker Hub pushen
          docker tag docker.io/library/catalog:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/catalog:latest 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/catalog:latest 
  

      - name: Upload Surefire Reports # Upload der Surefire Reports als Artefakt (Testresultate publizieren)
        if: always() # Immer ausführen, auch wenn vorherige Schritte fehlschlagen
        uses: actions/upload-artifact@v4 # Github Action zum Upload von Artefakten
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Jacoco Coverage # Upload der Jacoco Coverage Reports als Artefakt (Bonus)
        if: always() # Immer ausführen, auch wenn vorherige Schritte fehlschlagen
        uses: actions/upload-artifact@v4 # Github Action zum Upload von Artefakten
        with:
          name: catalog-coverage
          path: target/site/jacoco
